# Generated by Django 5.0.6 on 2024-06-25 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_name', models.CharField(blank=True, default='', max_length=255)),
                ('camera_ip', models.CharField(max_length=255)),
                ('camera_port', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'camera_tbl',
            },
        ),
        migrations.AddConstraint(
            model_name='camera',
            constraint=models.UniqueConstraint(fields=('camera_ip', 'camera_port'), name='unique_camera_ip_port'),
        ),
    ]
